### ISSUE TITLE
[Bug] Crashes Upon Start

### ISSUE THREAD

**Issue by Brithim** [nevoka-be/Issues#10]
**Describe the bug**
trying to run the mod and when trying to launch the game, while loading the mods, when it gets to Gamesense, it'll hang for a few moments and crash. 

**To Reproduce**
1. Install the mod with required libraries 
2. Launch the game
3. Crashes with exit error code 1
4. See error in logs below

**Expected behavior**
Install and profit?

**Screenshots**
![image](https://user-images.githubusercontent.com/22914585/156110621-e212711f-9e14-4e5c-98fa-1a845e80362c.png)
Current Game Ver & Loader:
![image](https://user-images.githubusercontent.com/22914585/156110718-d95b545c-483d-4e39-abef-d7519fd4f325.png)
Mods:
![image](https://user-images.githubusercontent.com/22914585/156110768-49fceb2a-3d73-436a-a081-63dd83c09764.png)

**Logs**
(https://gist.github.com/Brithim/e7c18ce4d68dd4ef89f085c9c56f94f6)
*line 85 and past is where the mod starts up and crashes*

**Desktop:**
 - OS: Win 10 (21H2)
 - Java Version Installed Through system (1.8.0.311-b11) Not sure for the Minecraft runtime
 - Mod+version [gamesense-1.18-1.13.25](https://www.curseforge.com/minecraft/mc-mods/steelseries-gamesense/files/3552879)

**Additional context**
Seems like the crashes could be fixed by changing the descriptor, not sure if that is the issue or what might be the fix. Just skimming the logs. Hopefully isn't too much of a hassle to fix. Cheers!

**Comment by JayJay1989** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/steelseries-gamesense-fabric/files/3681016
