### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by SleepyBoi2852** [nevoka-be/Issues#12]
**Describe the bug**
Gamesense Crashes on startup

**To Reproduce**
1. Copy mod to Mods folder
2. Start Minecraft
3. Crash Occurs

**Expected behavior**
I'm pretty sure it's supposed to start up

**Screenshots**
![image](https://user-images.githubusercontent.com/35126957/166096675-daa91552-f89b-4d8a-afaf-a7a13b76f545.png)

**Logs**
https://gist.github.com/SleepyBoi2852/ccd30417269ae12e3ab373b99275ab15

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version 17.0.2
 - Mod+version Gamesence 1.0.3

**Comment by SleepyBoi2852** [comment]
i also installed "Not Enough Crashes" so hopefully that helps

**Comment by JayJay1989** [comment]
For some reason mods i release on fabric breaks for 1.18. I need to look into it

**Comment by JayJay1989** [comment]
New release: https://www.curseforge.com/minecraft/mc-mods/steelseries-gamesense-fabric/files/3800977

**Comment by SleepyBoi2852** [comment]
Thanks. It works now
