### ISSUE TITLE
[Bug] Gamesense Minecraft Mod - Health in Multiplayer glitched

### ISSUE THREAD

**Issue by ChillyTheEevee** [nevoka-be/Issues#13]
**Describe the bug**
If you play in Multiplayer with the Health game event selected for your keyboard, then whenever anybody takes damage in the server the keyboard updates and switches between the colors of every player's health in the server at a fast rate. For example: If you have your keyboard set to turn red below 50% health and white above 50% health, and you also have two players on your server, one with 10% health and the other with 100%, then the keyboard will speedily change colors at a rate of what appears to be once every in game tick between white and red. If I had to guess, the keyboard is set to check every players health, not the health of the user.

**To Reproduce**
1. Create a Minecraft server with 2 or more players, I'm running on Paper.
2. Set your keyboard to change colors depending on health, I'm using  a color range with 5 different intervals each 20% apart.
3. Have one player take damage while the other has not
4. See your keyboard spaz out

**Expected behavior**
Ideally, in multiplayer the keyboard should light different colors depending on the user's health, not EVERY user's health.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Java Version: 1.8.0_321-b07
 - Mod+version: fabric-gamesense-mod-1.18.2-1.0.4.jar - Minecraft 1.18.2

**Additional information
- I am also running optifabric as well as Optifine 1.18.2, but i doubt thats the issue.

**Comment by JayJay1989** [comment]
@ChillyTheEevee what type of keyboard are you using?

**Comment by ChillyTheEevee** [comment]
Ah, my apologies. Im using an Apex 3 keyboard with Steelseries GG. @JayJay1989

**Comment by ChillyTheEevee** [comment]
the settings i have set are as follows:
![image](https://user-images.githubusercontent.com/103384393/170183846-a526cb46-f211-4324-93fb-31c0517d2d1a.png)

**Comment by JayJay1989** [comment]
Is been fixed in the new version
