### ISSUE TITLE
[Bug] rival 5 light flashing

### ISSUE THREAD

**Issue by neonyxiaa** [nevoka-be/Issues#14]
**Describe the bug**
the mod is causing my rival 5 mouse's left light flash white

**To Reproduce**
1. add the mod to my minecraft mods folder
2. start up the game 
3. turn on the gamesense app on the steelseries gg engine app 
4. it starts flashing

**Expected behavior**
not flash

**Screenshots**
i cant but its quite self explanatory

**Logs**
nothing crashes

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Java Version openjdk 18
 - Mod+version the newest version of the fabric one for 1.19.2

**Additional context**
it doesnt do this on the right side of the mouse, only the left

**Comment by neonyxiaa** [comment]
it appears to only do this on this  paper server, but still a bug nonetheless

**Comment by JayJay1989** [comment]
Should be fixed in the new version
