### ISSUE TITLE
[Bug] not available for 1.20

### ISSUE THREAD

**Issue by GearzGT** [nevoka-be/Issues#15]
**Describe the bug**
this mod is not available for 1.20 
**To Reproduce**
not applicable

**Expected behavior**
steelseries still says Minecraft should work, so i would expect it to work on the current version of Minecraft in both forge and fabric.

**Screenshots**
not applicable

**Logs**
not applicable

**Desktop (please complete the following information):**
 - OS: windows: 11
 - Java Version: ?
 - Mod+version: Steelseries Gamesense [Fabric] 1.91

**Additional context**
1.20 has been out for 4 months and no information on this mod getting updated.

**Comment by JayJay1989** [comment]
The mod needed some changes to not run on the render thread, users reported fps issues and its fixed.
[Forge](https://www.curseforge.com/minecraft/mc-mods/steelseries-gamesense/files/4803358)
[Fabric](https://curseforge.com/minecraft/mc-mods/steelseries-gamesense-fabric/files/4803359)

**Comment by GearzGT** [comment]
fabric still doesn't show up as 1.20 as of 5 hours after your comment. Forge does show up
![image](https://github.com/nevoka-be/Issues/assets/147269614/52ab813c-fbaa-4217-b217-2693c46d7f44)
