### ISSUE TITLE
[Bug] Gamesense not available on curseforge

### ISSUE THREAD

**Issue by GearzGT** [nevoka-be/Issues#16]
**Describe the bug**
fabrick is still not showing 1.20

**To Reproduce**
![image](https://github.com/nevoka-be/Issues/assets/147269614/7ad57ab1-2399-4d28-b139-fce8ea37d926)

**Expected behavior**
it should have been here but its not. 
**Screenshots**
![image](https://github.com/nevoka-be/Issues/assets/147269614/3d1d0e45-3360-4139-a3fd-9086a67ad6f9)

**Logs**
/ 

**Desktop (please complete the following information):**
 - OS: windows 11
 - Java Version ?
 - Mod+version missing 1.20

**Additional context**
sorry for opening another issue, but i checked again today and its not available for fabric. apologies again.

**Comment by JayJay1989** [comment]
@GearzGT Its under manual review
![image](https://github.com/nevoka-be/Issues/assets/1212803/8025a60e-fb45-4e4a-ba11-494f17267344)

**Comment by GearzGT** [comment]
alright, i thought it was something like that but wanted to be sure, thanks for the fast reply. cant wait till its available so i can use it.

**Comment by JayJay1989** [comment]
@GearzGT its been approved as of [Oct 23 12pm UTC](https://dateful.com/convert/utc?t=12&d=2023-10-23)
