### ISSUE TITLE
[Bug] 1.20 forge makes the game crash on startup with exit code 1

### ISSUE THREAD

**Issue by GearzGT** [nevoka-be/Issues#17]
**Describe the bug**
i tried to add the gamesence 1.20 mod to 2 modpacks and as the single mod on its own and all 3 crash when loading the mods, giving exit code 1.

**To Reproduce**
1. add gamesence 1.20 to any modpack or a brand new pack as the only mod.
2. load up the launcher
3. hit play
4. wait for game to crash

**Expected behavior**
the game to work

**Screenshots**
![image](https://github.com/nevoka-be/Issues/assets/147269614/d79d4572-4701-40f3-a96e-4e0a8eda7e90)

**Logs**
/ 

**Desktop (please complete the following information):**
 - OS: windows 11
 - Java Version: no idea
 - Mod+version [1.20.x] gamesense-1.20-1.15.0

**Additional context**
hate to bother you so much but it doesn't work still

**Comment by JayJay1989** [comment]
@GearzGT  can you provide me a crashlog?

**Comment by GearzGT** [comment]
@JayJay1989  how would i do that?

**Comment by GearzGT** [comment]
damn sorry i didnt mean to close the issue, i thought it was a toggle

**Comment by GearzGT** [comment]
@JayJay1989 i think this is it? https://pastebin.com/aRERjqtM if not i might need to be talked through how to do it

**Comment by GearzGT** [comment]
wait, is this the issue? 
[21:14:45] [main/FATAL]: Failed to parse version spec [1.20)
org.apache.maven.artifact.versioning.InvalidVersionSpecificationException: Single version must be surrounded by []: [1.20)
so making it [1.20] would fix it? (i have no idea how or where to do that, just trying to help/save you time/learn something)

**Comment by JayJay1989** [comment]
Fixed, you can expect an update in some minutes
![image](https://github.com/nevoka-be/Issues/assets/1212803/6fe7c244-3307-45a7-9d16-b8312c909b30)

**Comment by JayJay1989** [comment]
> wait, is this the issue? [21:14:45] [main/FATAL]: Failed to parse version spec [1.20) org.apache.maven.artifact.versioning.InvalidVersionSpecificationException: Single version must be surrounded by []: [1.20) so making it [1.20] would fix it? (i have no idea how or where to do that, just trying to help/save you time/learn something)

it was "[1.20,)" 🙃
