### ISSUE TITLE
[Bug] Config file generates incorrectly

### ISSUE THREAD

**Issue by Moleculor** [nevoka-be/Issues#3]
I went to this mod: https://www.curseforge.com/minecraft/mc-mods/better-bedrock-generator
and it brought me *here* to submit issues? Hopefully that's right?

**Describe the bug**
Instead of

`dimensionFilter = ["minecraft:overworld", "minecraft:the_nether"]`

in the config it generates as

`dimensionFilter = ["minecraft:dimension", "minecraft:dimension"]`

This creates a bedrock ceiling in The End that the dragon (and exit portal) are above (and inaccessible).

**To Reproduce**
1. Install Minecraft 1.16.4.
2. Install Forge 35.1.10
3. Install Better Bedrock Generator 0.1.0.
4. Run the whole thing.

**Comment by JayJay1989** [comment]
Thanks for reporting. Will ook into it

**Comment by JayJay1989** [comment]
Fixed in: https://www.curseforge.com/minecraft/mc-mods/better-bedrock-generator/files/3133643
