### ISSUE TITLE
[Bug] Huge issue with the End generation. spawns a layer of bed rock above everything and also moves the dragon pirch thing up there to. It also completely removes end biomes from the game. No forests or City's. The mod was being used with Biomes O Plenty.

### ISSUE THREAD

**Issue by Eighiethworld** [nevoka-be/Issues#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Please use a paste site for large blocks of code/logs: https://gist.github.com/

**Desktop (please complete the following information):**
 - Java Version [e.g. 1.8u252]
 - Mod+version [e.g. BetterBedrockGenerator 0.0.6]

**Additional context**

**Comment by JayJay1989** [comment]
Can you please use the template? i dont have any idea which version of BetterBedrockGenerator

**Comment by JayJay1989** [comment]
can be referenced to #3
