### ISSUE TITLE
1.16.5 on CurseForge

### ISSUE THREAD

**Issue by leyxcx** [nevoka-be/Issues#7]
This isn't a bug or anything, but the mod being marked as 1.16.4 on Curse means it can't be used in 1.16.5 in any modpacks or be downloaded through any launchers for .5. Could this please be marked as 1.16.5?

**Comment by JayJay1989** [comment]
About which mod are we talking?

**Comment by leyxcx** [comment]
oops sorry, I didn't realise this was an issues page for all mods. The better bedrock generator mod for forge :)

**Comment by JayJay1989** [comment]
Will look into it within a hour. Thanks for letting me know
