### ISSUE TITLE
Game seems to crash on startup 1.18.1 ATLauncher [Bug]

### ISSUE THREAD

**Issue by SHADO-SYSTEM** [nevoka-be/Issues#8]
**Describe the bug**
While using ATLauncher (fabric variant) game seems to crash once it's launched. Game version 1.18.1

**To Reproduce**
1. Launch ATLauncher (version 3.4.10.11)
2. Add the mod (gamsense fabric 1.18.1)
3. Other mods added (fabric(0.12.12), fabric-api(0.44.0), cloth-config(6.1.48))
4. Launch the game via ATLauncher
5. Error (will add error log down the list)

**Expected behavior**
The game to launch? Not sure what to write here...

**Screenshots**
Will add a full error log instead because screenshots won't help much in this issue.

**Logs**
[Error Log.txt](https://github.com/nevoka-be/Issues/files/7796324/Error.Log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version : 17 (17.0.1)
 - Mod+version : fabric-gamsense-mod-1.18-1.0.2

**Additional context**
Game launch tested with only fabric mod installed.
SteelSeries engine version (12.2.0).

**Comment by JayJay1989** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/steelseries-gamesense-fabric/files/3681016
