### ISSUE TITLE
[Bug] Game crashes upon clicking 'Play' - Fabric Loader 1.18.1

### ISSUE THREAD

**Issue by Artsm3iH** [nevoka-be/Issues#9]
**Describe the bug**
Game crashes after clicking 'Play' through the launcher.

'An unexpected error occurred and the game crashed. We are sorry for this inconvenience.

Closecode: 0'

**To Reproduce**
1. Go to 'Minecraft Launcher (windows store edition)'
2. Click on 'Play - (Fabric loader 1.18.1)'
4. See error described above

**Expected behavior**
Game launcher with SteelSeries engine mod working.

**Screenshots**
![Screenshot_63](https://user-images.githubusercontent.com/5630499/148683487-6c0087e7-fbfe-4a5d-8a6e-c1e13548946c.jpg)

**Logs**
(https://gist.github.com/Artsm3iH/a055fb4c3214787a9aff4a3590e20540)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version: 17
 - Mod+version: Gamesense 1.18-1.0.2

**Comment by JayJay1989** [comment]
Ik probeer dit de eerstkomende dagen op te lossen, dank je om dit te rapporteren

**Comment by Artsm3iH** [comment]
Thanks!

**Comment by Artsm3iH** [comment]
Good evening, did you manage to have a look yet? @JayJay1989

**Comment by JayJay1989** [comment]
Didn't had the time to look yet. Will look when i have some spare time

**Comment by JayJay1989** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/steelseries-gamesense-fabric/files/3681016
